import Script from "next/script";
import '../assets/styles/globals.css';
import ChatbotButton from '@/components/chatbot/ChatbotButton';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className="bg-bg">
        <Script
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_API_KEY}&libraries=services,clusterer&autoload=false`}
          strategy="beforeInteractive"
        />
        {children}
        {/* <Footer/> */}
        <ChatbotButton />
      </body>
    </html>
  );
}
